env:
  browser: true
  es2021: true
  node: true
extends: standard
plugins:
  - jsdoc
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  comma-dangle: [error, always-multiline]
  key-spacing: ["error", { "mode": "minimum" }]
  no-multi-spaces: [error, { exceptions: { Property: true, ObjectExpression: true }}]
